### ISSUE TITLE
Exception when attempting to download a file to an existing filename

### ISSUE THREAD

**Issue by GuutBoy** [Sepior/java-s3-demo#1]
Running twice the download command 
```
java -jar target/java-s3-demo-0.0.0-SNAPSHOT-jar-with-dependencies.jar download sepior-demo mykey test2.txt
```

as described in the demo guide results in an uncaught exception 

```
Mar 17, 2017 11:33:55 AM com.amazonaws.services.s3.internal.S3AbortableInputStream close
WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
Exception in thread "main" java.nio.file.FileAlreadyExistsException: test2.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at com.sepior.s3.demo.S3EncryptionDemo.downloadUsingAmazonSDK(S3EncryptionDemo.java:79)
	at com.sepior.s3.demo.S3EncryptionDemo.main(S3EncryptionDemo.java:117)
```
You could probably handle that more elegantly.

**Comment by MicOestergaard** [comment]
This issue has been fixed.
